version: "3.3"
services:
  api:
    ports:
      - 8011:8011
    env_file: .env_docker
    volumes:
      - ./:/app
      - /app/node_modules
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    networks:
      - dockerNet
  db:
    image: postgres:latest
    ports:
      - 8012:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: wbd_db_rest
    volumes:
      - ./postgres:/var/lib/postgres
    networks:
      - dockerNet
  redis:
    image: redis:latest
    ports:
      - 8013:6379
    volumes:
      - ./redis:/data
    networks:
      - dockerNet
networks:
  dockerNet:
    external:
      true
